parse.cpp File Reference
#include `calculate.h`
#include `frame.h`
#include `parse.h`
#include `simul.h`
#include <cstdio>
#include <fstream>
#include <regex>
#include <string>
#include <vector>
Functions
void process_line (std::string line, Frame &frame)
Takes info from data file and populates Frame object.
bool check_dimension (Frame &frame)
Check if simulation output data is 2D or 3D, returns true if 3D.
void process_frame (Frame &frame)
Takes info from Frame object, then creates and populates Linker objects.
void get_output_file_contents (std::string fileName, Simul &simul)
Extract and process data from output file previously created by Cytosim.
void get_simulation_params (Simul &simul, std::string fileName)
Obtain simulation parameters from *.cym Cytosim config file.
Function Documentation
check_dimension()
bool check_dimension (Frame & frame)
Check if simulation output data is 2D or 3D, returns true if 3D.
Parameters
frame - reference to Frame object
Returns
threeDimData - bool
Todo
Todo Works with 3D output file, need to check that it returns false for a 2D output file.
Definition at line 93 of file parse.cpp.
{
    std::regex rgx("pos[12]Z"); // check if Z coordinate is present
    std::smatch match ;
    bool threeDimData ;
    std::vector <std::string>::iterator dataPtr = frame.dataCategories.begin(),
                                        endPtr = frame.dataCategories.end() ;
    do
    {
            threeDimData = std::regex_search(*dataPtr, match, rgx) ;
            ++dataPtr ;
    } while (!threeDimData && dataPtr != endPtr) ;
    return threeDimData ;
}
References Frame::dataCategories, and frame.
Referenced by process_frame().
get_output_file_contents()
void get_output_file_contents (std::string fileName, Simul & simul)
Extract and process data from output file previously created by Cytosim.
Parameters
fileName - std::string
simul - reference to Simul object
Used as reference: https://thispointer.com/c-how-to-read-a-file-line-by-line-into-a-vector/
Definition at line 195 of file parse.cpp.
{
    // open file
    std::ifstream dataFile(fileName.c_str());
    while (dataFile)
    {
        // Define string variable
        std::string line ;
        int frameIdx = 0;
        // static const Frame emptyFrame;
        Frame currentFrame;
        Frame previousFrame ;
        // simul.wDotIntegral = 0.0 ;
        // Read line by line and sort into frames
        // line is a c string
        while (std::getline(dataFile, line))
        {
            std::size_t foundEnd ;
            foundEnd = line.find(currentFrame.endStr);
            // If the line does not match endString
            // fun fact: if (foundEnd == std::string::npos) does produce desired results
            // which is why the "double negative"/(!(!=)) is necessary
            if (!(foundEnd != std::string::npos))
            {
                process_line(line, currentFrame);
            }
            else // If line DOES match endString
            {
                process_frame(currentFrame) ;
                frameIdx++ ;
                calculate_frame(currentFrame, previousFrame, simul) ;
                // Move current frame object to previousFrame
                previousFrame = currentFrame ;
                // Create new frame object
                currentFrame = Frame() ;
            }
        }
    printf("Total number of frames: %d\n", frameIdx);
    }
    //Close The File
    dataFile.close();
}
References calculate_frame(), Frame::endStr, process_frame(), process_line(), and simul.
Referenced by main().
get_simulation_params()
void get_simulation_params (Simul & simul, std::string fileName)
Obtain simulation parameters from *.cym Cytosim config file.
Parameters
simul - reference to Simul object
fileName - std::string
Definition at line 254 of file parse.cpp.
{
    //simul.unloadedSpeed
    std::regex rgxUnload("unloaded_speed");
    //simul.stallForce ;
    std::regex rgxStall("stall_force");
    std::regex rgxFloat("-?\\d+\\.?\\d*") ;
    // open file
    std::ifstream configFile(fileName.c_str());
    while (configFile)
    {
        std::string line ;
        while (std::getline(configFile, line))
        {
            std::smatch matchLine ;
            std::smatch matchFloat ;
            if (std::regex_search(line, matchLine, rgxUnload))
            {
                if (std::regex_search(line, matchFloat, rgxFloat))
                    simul.unloadedSpeed = std::stof(matchFloat.str(0));
            }
            else if (std::regex_search(line, matchLine, rgxStall))
            {
                if (std::regex_search(line, matchFloat, rgxFloat))
                    simul.stallForce = std::stof(matchFloat.str(0));
            }
        }
        printf("unloaded_speed: %f\n",simul.unloadedSpeed) ;
        printf("stall_force: %f\n", simul.stallForce) ;
        printf("\n") ;
    }
    configFile.close() ;
}
References simul, Simul::stallForce, and Simul::unloadedSpeed.
Referenced by main().
process_frame()
void process_frame (Frame & frame)
Takes info from Frame object, then creates and populates Linker objects.
Parameters
frame - reference to Frame object
Definition at line 118 of file parse.cpp.
{
    bool threeDimData = check_dimension(frame) ;
    for (auto line : frame.dataLines)
    {
        if (line.size() > 0)
        {
            Linker linker ;
            linker.classOfObject = std::stoi(line.at(0)) ;
            linker.linkerIdentity = std::stoi(line.at(1)) ;
            linker.handOne.fiberIdentity = std::stoi(line.at(2)) ;
            linker.handOne.abscissa = std::stof(line.at(3)) ;
            if (threeDimData)
            {
                linker.handOne.positionVector_std.push_back(std::stof(line.at(4))) ;
                linker.handOne.positionVector_std.push_back(std::stof(line.at(5))) ;
                linker.handOne.positionVector_std.push_back(std::stof(line.at(6))) ;
                linker.handOne.positionVector_eigen = convert_std_vec_to_eigen_vec(linker.handOne.positionVector_std) ;
                linker.handTwo.fiberIdentity = std::stoi(line.at(7)) ;
                linker.handTwo.abscissa = std::stof(line.at(8)) ;
                linker.handTwo.positionVector_std.push_back(std::stof(line.at(9))) ;
                linker.handTwo.positionVector_std.push_back(std::stof(line.at(10))) ;
                linker.handTwo.positionVector_std.push_back(std::stof(line.at(11))) ;
                linker.handTwo.positionVector_eigen = convert_std_vec_to_eigen_vec(linker.handTwo.positionVector_std) ;
                linker.force = std::stof(line.at(12)) ;
                linker.cosAngle = std::stof(line.at(13)) ;
            }
            else
            {
                linker.handOne.positionVector_std.push_back(std::stof(line.at(4))) ;
                linker.handOne.positionVector_std.push_back(std::stof(line.at(5))) ;
                linker.handOne.positionVector_eigen = convert_std_vec_to_eigen_vec(linker.handOne.positionVector_std) ;
                linker.handTwo.fiberIdentity = std::stoi(line.at(6)) ;
                linker.handTwo.abscissa = std::stof(line.at(7)) ;
                linker.handTwo.positionVector_std.push_back(std::stof(line.at(8))) ;
                linker.handTwo.positionVector_std.push_back(std::stof(line.at(9))) ;
                linker.handTwo.positionVector_eigen = convert_std_vec_to_eigen_vec(linker.handTwo.positionVector_std) ;
                linker.force = std::stof(line.at(10)) ;
                linker.cosAngle = std::stof(line.at(11)) ;
            }
            frame.linkerObjects.push_back(linker) ;
            frame.numLinkers = frame.linkerObjects.size() ;
        }
        else
            frame.numLinkers = 0 ;
    }
}
References Hand::abscissa, check_dimension(), Linker::classOfObject, convert_std_vec_to_eigen_vec(), Linker::cosAngle, Frame::dataLines, Hand::fiberIdentity, Linker::force, frame, Linker::handOne, Linker::handTwo, linker, Linker::linkerIdentity, Frame::linkerObjects, Frame::numLinkers, Hand::positionVector_eigen, and Hand::positionVector_std.
Referenced by get_output_file_contents().
process_line()
void process_line (std::string line, Frame & frame)
Takes info from data file and populates Frame object.
Parameters
line - std::string
frame - reference to Frame object
Definition at line 17 of file parse.cpp.
{
    std::smatch match ;
    if (line.find(frame.frameStr) != std::string::npos)
    { // Extract int with frame number
        std::regex rgx("\\d+");
        if (std::regex_search(line, match, rgx))
            frame.frameNumber = std::stoi(match.str(0));
    }
    else if (line.find(frame.timeStr) != std::string::npos)
    { // Extract float with time stamp
        std::regex rgx("\\d+.\\d+");
        if (std::regex_search(line, match, rgx))
            frame.timeStamp = std::stof(match.str(0));
    }
    else if (line.find(frame.reportStr) != std::string::npos)
    { // Extract string with report command used to generate data file
        std::regex rgx("\\w+:\\w+");
        if (std::regex_search(line, match, rgx))
            frame.reportCommand = match.str(0);
    }
    else if (line.find(frame.categoriesStr) != std::string::npos)
    {
        // Extract string with category names of data in file
        std::regex rgx("\\w+") ;
        auto categoriesBegin = std::sregex_iterator(line.begin(), line.end(), rgx);
        auto categoriesEnd = std::sregex_iterator() ;
        for (std::sregex_iterator i = categoriesBegin; i != categoriesEnd; ++i)
        {
            match = *i ;
            std::string matchStr = match.str() ;
            frame.dataCategories.push_back(matchStr);
        }
        // maybe eventually will have some code which auto-detects categories
        // and creates a linker class with appropriate variables
    }
    else
    {
        // Extract vector of strings of data lines for the frame
        std::regex rgx("-?\\d+\\.?\\d*");
        // https://en.cppreference.com/w/cpp/regex/regex_iterator
        auto dataBegin = std::sregex_iterator(line.begin(), line.end(), rgx);
        auto dataEnd = std::sregex_iterator();
        std::vector <std::string> dataEntries ;
        for (std::sregex_iterator i = dataBegin; i != dataEnd; ++i)
        {
            match = *i ;
            std::string matchStr = match.str();
            dataEntries.push_back(matchStr) ;
        }
        frame.dataLines.push_back(dataEntries) ;
    }
}
References Frame::categoriesStr, Frame::dataCategories, Frame::dataLines, frame, Frame::frameNumber, Frame::frameStr, Frame::reportCommand, Frame::reportStr, Frame::timeStamp, and Frame::timeStr.
Referenced by get_output_file_contents().